### ISSUE TITLE
Database maintenance

### ISSUE THREAD

**Issue by zware** [python/buildmaster-config#119]
Our database (`state.sqlite`) currently contains quite a lot of cruft, especially defunct workers and their associated builders.  It also predates several foreign key relationships added to the buildbot database model due to issues with getting migrations to play nicely with sqlite, so we can't simply delete the old workers without picking through every table to clear out related data.

To remedy this, I'd like to simply remove the old database and start fresh.  @pablogsal, @vstinner suggested that you may want to compute some statistics before doing so; do you, and if so do you need the database to be active or just need a copy?

**Comment by pablogsal** [comment]
> do you, and if so do you need the database to be active or just need a copy?

I do, but for that I just need a copy :)

**Comment by zware** [comment]
Ok, I've saved the old database for you at `~buildbot/old_state_backup_28Nov19.sqlite` on the master VM and started a fresh database.
