### ISSUE TITLE
Catch "test_code leaked [3, 4, 4] memory blocks, sum=11" as a test warning

### ISSUE THREAD

**Issue by vstinner** [python/buildmaster-config#14]
There are now buildbots running reference leaks tests. I would like to extract leaks as warnings. Example of leak:

```
test_code leaked [3, 4, 4] memory blocks, sum=11
```

http://buildbot.python.org/all/builders/x86%20Gentoo%20Refleaks%203.x/builds/46/steps/test/logs/stdio

I added the following regex to master/custom/steps.py:

```
        # test_os leaked [6, 6, 6] memory blocks, sum=18,
        r'test_.* leaked \[',
```

But it seems like the regex doesn't work, doesn't match or that the my config was not applied? I'm quite sure that the new config was applied. I tested manually the regex using the code from steps.py. I missed something...

See my commit 0d44a6a6b05fea13d8101c06e0db73112802c19a.

@zware: Would you mind to take a look?

**Comment by haypo** [comment]
Oh wait. I was looking at a build which ran yesterday. I made my config change yesterday. Maybe I just have to wait for the next build.

I missed that the buildbot slave ware-gentoo-x86 is now offline.

**Comment by zware** [comment]
@vstinner Is this working as you want it to?

**Comment by vstinner** [comment]
Oh sorry, I added a regex a long time ago. "test_code leaked [3, 4, 4] memory blocks, sum=11" is now in warnings, it works as expected, yes :-)
