### ISSUE TITLE
File permissions on uploaded test results are too restrictive

### ISSUE THREAD

**Issue by zware** [python/buildmaster-config#144]
See [this result](https://buildbot.python.org/test-results/3.x/PPC64%20Fedora%203.x/build_145.xml), for example.

```
-rw------- 1 buildbot buildbot 4.6M Jan  8 15:54 '/data/www/buildbot/test-results/3.x/PPC64 Fedora 3.x/build_145.xml'
```

This wasn't true previously, see [this result](https://buildbot.python.org/test-results/3.x/PPC64%20Fedora%203.x/build_138.xml):

```
-rwxr-xr-x 1 buildbot buildbot 4.6M Jan  7 17:05 build_138.xml
```

This appears to be due to `umask` being set to 0077 in the current master process:

```
$ grep Umask /proc/`pgrep -f buildbot.tac`/status
Umask:  0077
```

**Comment by pablogsal** [comment]
Seems that `FileUpload` has a `mode` option:

```
- ['mode']       file access mode for the resulting master-side file.
                 The default (=None) is to leave it up to the umask of
                 the buildmaster process.
```

What should be the desired permissions?

**Comment by zware** [comment]
Something world-readable, or at least readable by `www-data` :).  Otherwise, I'm not too bothered.
