### ISSUE TITLE
Increase parallelization of PPC64 builds

### ISSUE THREAD

**Issue by aixtools** [python/buildmaster-config#177]
The server used for AIX PPC64 builds has 16 core (64 hardware threads) and can easily support more parallelization  during the bot tests.

**Comment by aixtools** [comment]
Thanks.

But is it working? The last run still shows -j2.

```
./python -E -c 'import sys ; from sysconfig import get_platform ; print("%s-%d.%d" % (get_platform(), *sys.version_info[:2]))' >platform
./python  ./Tools/scripts/run_tests.py -j 1 -u all -W --slowest --fail-env-changed --timeout=900 -j2 --junit-xml test-results.xml 
== CPython 3.9.0a5+ (heads/master:5cd2803, Apr 9 2020, 11:11:59) [GCC 7.2.0]
== AIX-2-00FA74164C00-powerpc-32bit big-endian
== cwd: /home/shager/cpython-buildarea/3.x.edelsohn-aix-ppc64/build/build/test_python_8520020
== CPU count: 64
== encodings: locale=ISO8859-1, FS=iso8859-1
```

**Comment by vstinner** [comment]
I think you misunderstood parallel_tests=10: that's the number of parallel buildbot *jobs*. Not the -j option passed to python -m test.

**Comment by zware** [comment]
Hmm, no; `parallel_tests` should equate to the `-j` option to regrtest; `parallel_builders` would increase the number of buildbot jobs (builders) allowed to run at the same time.

**Comment by zware** [comment]
The change didn't appear to have been deployed; I've reconfigured the master and [started a build](https://buildbot.python.org/all/#/builders/227/builds/620); we'll see what it does.

**Comment by zware** [comment]
Other than a truly huge number of warnings in the compile step, the build seemed to go well.

**Comment by vstinner** [comment]
> The change didn't appear to have been deployed; I've reconfigured the master and started a build; we'll see what it does.

Strange. I deployed it manually.
