### ISSUE TITLE
Set up worker for ac_cv_posix_semaphores_enabled=no builder

### ISSUE THREAD

**Issue by zware** [python/buildmaster-config#203]
@paulproteus has offered to run a worker to test the `ac_cv_posix_semaphores_enabled=no` build that he's trying to fix in bpo-40692.  I suggested to fix the chicken-and-egg situation of not wanting a constantly failing builder and not wanting to merge a fix for an untested platform by going ahead and setting up the worker to run a regular build until python/cpython#20239 is ready to merge, at which time we could switch it over to use `ac_cv_posix_semaphores_enabled=no`.

I've not yet had time and memory coincide to get it set up, so I'm opening this issue in case anyone else does have time :)

**Comment by vstinner** [comment]
https://bugs.python.org/issue40692#msg370674

**Comment by paulproteus** [comment]
I'm interested in getting this going and supporting it. I have a stable place to host it. The reason I didn't chime in earlier was I wasn't sure I had a stable place for it.

One thing we can do is get me started with a generic Linux buildbot first to make sure machine works properly as a CPython buildbot. Once we've verified that, and once my other pull request gets merged, I'm interested in setting up the worker described in this pull request.

I think the next step is for me to get buildbot credentials to add my worker to the pool. When I asked Zach how to do that, he suggested I ping @vstinner and @pablogsal to do that, so I am doing that. :)

Let me know what you think. Cheers!

**Comment by zware** [comment]
Given Victor's three-year-old comment, I'm going to go ahead and close this.
