### ISSUE TITLE
make is not a good process manager

### ISSUE THREAD

**Issue by merwok** [python/buildmaster-config#211]
Hello!  The readme mentions `make` commands to start the buildbot, and I got flashbacks from a job where we had process issues because of make.  I’m afraid I don’t have solid references to share; the general idea is that make is designed to run commands over a graph of targets, but is not made to run a process, forwarding signals and exit codes, restarting, etc.  Now I don’t know what `bin/buildbot` does, maybe it’s a wrapper that handles all that and make is only used to kick that off, not monitor things properly, in which case my worry is unfounded.  But if make is really used as process supervisor on servers, I would suggest to use a tool made for that.  Cheers!

**Comment by vstinner** [comment]
"make start-master" spawns a deamon in background. It doesn't manage the process. I'm not sure which problem your are trying to solve.

**Comment by merwok** [comment]
Sounds good then!
