### ISSUE TITLE
Should triagers be able to stop builds?

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/buildmaster-config#260]
Hi, Python triagers can add `test-with-buildbots` label to PRs, but they cannot stop a build if it hangs. Currently, only core devs can do that. This makes it hard for triagers to "unstick" a PR after they test it with buildbots.

I think triagers should be able to stop builds. I will open a discussion at https://discuss.python.org/c/core-workflow/8. Please let me know if I should open a discussion at python-buildbots/python-dev too. Thanks for your time.

**Comment by zware** [comment]
I'm in favor of it; it should just take a change in https://github.com/python/buildmaster-config/blob/c7cae083d506d086f242325899a72e2fd23faae0/master/custom/auth.py#L7 if you want to take a stab at it.
