### ISSUE TITLE
`AMD64 Arch Linux Asan Debug` runs incomplete `git clean` before building

### ISSUE THREAD

**Issue by erlend-aasland** [python/buildmaster-config#274]
`AMD64 Arch Linux Asan Debug` runs `git clean -f -f -d` iso. `git clean -fdx`.

**Comment by erlend-aasland** [comment]
Seems like `AMD64 Arch Linux Asan Debug` is much happier now: https://buildbot.python.org/all/#/builders/586/builds/181

**Comment by pablogsal** [comment]
Thanks for the check and for #275!
