### ISSUE TITLE
Move Windows 11 worker to STABLE

### ISSUE THREAD

**Issue by jkloth** [python/buildmaster-config#294]
Ah, I though this was expected to succeed. In that case I will mark it as UNSTABLE for now

_Originally posted by @pablogsal in https://github.com/python/buildmaster-config/issues/289#issuecomment-933052836_

It's been a month living in the UNSTABLE set, and now a breaking change has made its way into the active branches.  The responsible PR was checked with `test-with-buildbots`, but since that only submits builds to STABLE, the faulty PR slipped through.

Please switch the worker back into STABLE to prevent this happening again.

PS: The failure just so happens to be related to the issue that got this worker moved to UNSTABLE in the first place.

**Comment by vstinner** [comment]
Right now, the worker is failing for 5 days: https://buildbot.python.org/all/#/builders/733

First failure is a test_winconsoleio fail: https://buildbot.python.org/all/#/builders/733/builds/243

**Comment by vstinner** [comment]
test_winconsoleio failure: https://bugs.python.org/issue45354

**Comment by jkloth** [comment]
Right, IF it would have been in STABLE, @zooba (when he ran his PR with `test-with-buildbots`) would not have pushed the changes that caused the failure (GH-29396).  The worker had been otherwise fine for the previous month.

**Comment by pablogsal** [comment]
@zooba maybe we can fix or revert https://github.com/python/cpython/pull/29396 ? What do you think?

**Comment by vstinner** [comment]
> @zooba maybe we can fix or revert python/cpython#29396 ? What do you think?

@zooba pushed changes: https://bugs.python.org/issue45220#msg405736

**Comment by vstinner** [comment]
Tests pass again on AMD64 Windows11 3.x: 6 builds completed successfully (some with warnings): https://buildbot.python.org/all/#/builders/733

**Comment by zware** [comment]
All current Windows builders are stable; closing.
