### ISSUE TITLE
We don't have a buildbot testing with `-O`

### ISSUE THREAD

**Issue by erlend-aasland** [python/buildmaster-config#325]
In python/cpython#92886, Irit noticed that a bunch of tests fail when run with `-O`:

> On main (3.12 branch):
>
> % ./python.exe -Om test -j2
> [...]
> 10 tests failed:

[...]

> This seems wrong because
> (1) it indicates that some assertions should be exceptions instead.
> (2) it implies that we don't have a buildbot testing with -O

**Comment by vstinner** [comment]
I suggest you to contact the owner of one of existing buildbots and ask if they would be ok to add -O option to their worker. I don't think that it's worth it to add a new worker just for that.
