### ISSUE TITLE
New worker request: itamaro-win64-srv-22-aws

### ISSUE THREAD

**Issue by itamaro** [python/buildmaster-config#392]
### Username

itamaro

### GitHub username

@itamaro

### Name

Itamar Oren

### Password status

I will use an existing owner password

### Processor architecture

amd64

### Operating System

Windows Server 2022

### Anything special about the worker?

AWS hosted Windows worker for NoGIL builds

**Comment by vstinner** [comment]
> AWS hosted Windows worker for NoGIL builds

Nice!
