### ISSUE TITLE
New worker request: opsec-fbsd14

### ISSUE THREAD

**Issue by opsec** [python/buildmaster-config#393]
### Username

opsec

### Name

Kurt Jaeger

### Email address

buildbot-fbsd@opsec.eu

### Password status

I need a new owner password

### Processor architecture

amd64

### Operating System

FreeBSD 14.0-BETA1

**Comment by vstinner** [comment]
@zware: Would you mind to have a look at this request? Tell me if you want me to handle it.

**Comment by zware** [comment]
I have added owner configuration to the master, password to be emailed shortly.

@opsec, would you mind to open a PR to add your workers to the configuration?  You can use #388 as a guide.

**Comment by vstinner** [comment]
What's the status?

**Comment by vstinner** [comment]
FreeBSD 13 buildbot https://buildbot.python.org/all/#/builders/1223 is now green!

**Comment by opsec** [comment]
status: @work, getting buildbot to run.

**Comment by opsec** [comment]
> I have added owner configuration to the master, password to be emailed shortly.
> 
> @opsec, would you mind to open a PR to add your workers to the configuration? You can use #388 as a guide.

There's #393 and #394 to add opsec-fbsd14 and opsec-fbsd15.

**Comment by opsec** [comment]
Ah, now I get it! I'm supposed to create a pull request with a diff to the python/buildmaster-config repo. Done in https://github.com/python/buildmaster-config/pull/403

**Comment by opsec** [comment]
Will do as soon as my twistd.log tells me that it was able to do some build jobs. Right now it still says:
unauthorized login; check worker name and password

**Comment by vstinner** [comment]
Hum, apparently, you didn't fill information about yourself nor details in your builder configuration. The UI says:

* Admin: Your Name Here <admin@youraddress.invalid>
* Host: Please put a description of this build host here

I suppose that it's a config to set in the builder side. Can you please to complete it? Mention the OS name and version, number of CPU/memory, etc.

**Comment by vstinner** [comment]
I forced a build. It failed on the git step :-( Did you install git and other dependencies to build Python?

```
Upon execvpe b'git' [b'git', b'--version'] in environment id 2693540203392
:Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/process.py", line 432, in _fork
    self._execChild(path, uid, gid, executable, args, environment)
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/process.py", line 503, in _execChild
    os.execvpe(executable, args, environment)
  File "/usr/local/lib/python3.9/os.py", line 583, in execvpe
    _execvpe(file, args, env)
  File "/usr/local/lib/python3.9/os.py", line 616, in _execvpe
    raise last_exc
  File "/usr/local/lib/python3.9/os.py", line 607, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory: b'/home/buildbot/bin/git'
```

build: https://buildbot.python.org/all/#/builders/1232/builds/1

**Comment by opsec** [comment]
> I forced a build. It failed on the git step :-( Did you install git and other dependencies to build Python?

Sorry, I missed git, @work. I think I have all stuff necessary to build python, but one can never be sure in this depedency hell 8-}

**Comment by opsec** [comment]
> Hum, apparently, you didn't fill information about yourself nor details in your builder configuration. The UI says:
> 
>     * Admin: Your Name Here [admin@youraddress.invalid](mailto:admin@youraddress.invalid)
> 
>     * Host: Please put a description of this build host here
> 
> 
> I suppose that it's a config to set in the builder side. Can you please to complete it? Mention the OS name and version, number of CPU/memory, etc.

I updated the 14er buildbot config with admin & info, do I need to restart to sync that or how is it sent to the master ?

**Comment by opsec** [comment]
> > I forced a build. It failed on the git step :-( Did you install git and other dependencies to build Python?
> 
> Sorry, I missed git, @work. I think I have all stuff necessary to build python, but one can never be sure in this depedency hell 8-}

git done on both buildbot hosts.

**Comment by vstinner** [comment]
Build 4 is a success and has all builder info completed, thanks!

https://buildbot.python.org/all/#/builders/1232/builds/4

* Owner: Kurt Jaeger <buildbot-fbsd@opsec.eu> 
* Host: FreeBSD 14.0-BETA3, 16 GB vRAM, 8 vCores, amd64
