### ISSUE TITLE
New worker request: opsec-fbsd15

### ISSUE THREAD

**Issue by opsec** [python/buildmaster-config#394]
### Username

opsec

### Name

Kurt Jaeger

### Email address

buildbot-fbsd@opsec.eu

### Password status

I will use an existing owner password

### Processor architecture

amd64

### Operating System

FreeBSD 15-CURRENT

**Comment by vstinner** [comment]
@zware: Would you mind to have a look at this request? Tell me if you want me to handle it.

**Comment by vstinner** [comment]
What's the status?

**Comment by vstinner** [comment]
Tests pass, builder info completed: all good.

https://buildbot.python.org/all/#/builders/1238/builds/2
