### ISSUE TITLE
`master.utils` submodule fails to import

### ISSUE THREAD

**Issue by AlexWaygood** [python/buildmaster-config#412]
```shell
(venv) C:\Users\alexw\coding\buildmaster-config>python -c "import master.utils"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\alexw\coding\buildmaster-config\master\utils.py", line 3, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (C:\Users\alexw\coding\buildmaster-config\venv\Lib\site-packages\jinja2\__init__.py)
```

`jinja.Markup` doesn't exist with `Jinja2==3.1.2`.

Not sure if this submodule is really needed? (I don't really know anything about this codebase.)

**Comment by vstinner** [comment]
REPLACEMENTS and changecommentlink are no longer used. Do you want to propose a PR to remove this file?

**Comment by AlexWaygood** [comment]
> REPLACEMENTS and changecommentlink are no longer used. Do you want to propose a PR to remove this file?

Filed #413 to do that. FYI, I found this by running mypy on the codebase -- was curious to see if it would spot anything obvious after https://github.com/python/buildmaster-config/pull/409#issuecomment-1740571764 slipped through unnoticed :-)

**Comment by vstinner** [comment]
I should run pyflakes to detect such obvious mistake, twice.
