### ISSUE TITLE
New worker request: kushaldas-wasi

### ISSUE THREAD

**Issue by kushaldas** [python/buildmaster-config#442]
### Username

kushaldas

### Email address

mail@kushaldas.in

### Password status

I need a new owner password

### Processor architecture

amd64

### Operating System

Ubuntu 20.04

### Anything special about the worker?

For WASI builds, fresh setup.

**Comment by itamaro** [comment]
Hey @kushaldas, thank you for your interest in setting up a new buildbot worker for CPython!
I have updated the buildbot master configuration and I will be emailing you shortly on the email address you specified with your worker password.

Note that you will need to follow up with a PR to add the specific worker!
