### ISSUE TITLE
New worker request: <onder-riscv64>

### ISSUE THREAD

**Issue by furkanonder** [python/buildmaster-config#467]
### Username

onder

### Name

riscv64

### Email address

furkanonder@protonmail.com

### Password status

I need a new owner password

### Processor architecture

riscv64

### Operating System

Ubuntu 23.10 riscv64

**Comment by zware** [comment]
Hi @furkanonder.  I'm on board with getting this added, but haven't yet found the chance to make the changes to do so.  Would you mind making a PR for this?  #404 should be a reasonable template to follow.

**Comment by vstinner** [comment]
What's the status of riscv64 support in Python? Does Python build? Does the full test suite pass?

If Python doesn't build or if some tests are failing, are you going to propose fixes?

**Comment by vstinner** [comment]
There is a project to add the RISC-V architecture to Fedora: https://fedoraproject.org/wiki/Architectures/RISC-V Currently, they are using their own build server: http://fedora.riscv.rocks/koji/ I looked for "python3.12" and I found a recent log: http://fedora.riscv.rocks/kojifiles/packages/python3.12/3.12.2/1.fc40/data/logs/riscv64/build.log

Oh, great, the package builds successfully and **all tests pass** in 22 min!

```
== Tests result: SUCCESS ==

10 slowest tests:
- test.test_multiprocessing_spawn.test_processes: 5 min 8 sec
- test.test_multiprocessing_forkserver.test_processes: 2 min 59 sec
- test_tarfile: 2 min 43 sec
- test_regrtest: 2 min 41 sec
- test.test_multiprocessing_spawn.test_manager: 2 min 41 sec
- test.test_multiprocessing_spawn.test_misc: 2 min 18 sec
- test_socket: 1 min 57 sec
- test_multiprocessing_main_handling: 1 min 49 sec
- test.test_asyncio.test_ssl: 1 min 43 sec
- test_lib2to3: 1 min 38 sec

17 tests skipped:
    test.test_asyncio.test_windows_events
    test.test_asyncio.test_windows_utils test.test_gdb.test_backtrace
    test.test_gdb.test_cfunction test.test_gdb.test_cfunction_full
    test.test_gdb.test_misc test.test_gdb.test_pretty_print
    test_devpoll test_ioctl test_kqueue test_launcher test_msilib
    test_perf_profiler test_startfile test_winconsoleio test_winreg
    test_wmi

12 tests skipped (resource denied):
    test_curses test_ossaudiodev test_smtpnet test_socketserver
    test_tix test_tkinter test_ttk test_urllib2net test_urllibnet
    test_winsound test_xmlrpc_net test_zipfile64

459 tests OK.

Total duration: 22 min 44 sec
Total tests: run=41,785 (filtered) skipped=1,385
Total test files: run=476/488 (filtered) skipped=17 resource_denied=12
Result: SUCCESS
```

In that case, I'm fine with adding a buildbot.

@furkanonder: Tell me if you need help to create a PR to add a worker. See @zware's comment.

**Comment by furkanonder** [comment]
> but haven't yet found the chance to make the changes to do so.

I was following the [Devguide's Buildbot Section](https://devguide.python.org/testing/new-buildbot-worker/) and didn't notice any template sections. Thank you for your comment!

**Comment by furkanonder** [comment]
> What's the status of riscv64 support in Python? Does Python build? Does the full test suite pass?

Buildbot's details:
```
OS: Ubuntu 23.10 riscv64 
Host: StarFive VisionFive 2 v1.3B
```
Configuration: `./configure --with-pydebug`
Output: [configure-output.txt](https://github.com/python/buildmaster-config/files/14547500/configure-output.txt)

Build: `make -j`
Output: [make-output.txt](https://github.com/python/buildmaster-config/files/14547503/make-output.txt)

Test: `./python -m test -j4`
Output:
```
== Tests result: SUCCESS ==

13 tests skipped:
    test.test_asyncio.test_windows_events
    test.test_asyncio.test_windows_utils test_devpoll test_ioctl
    test_kqueue test_launcher test_msvcrt test_perf_profiler
    test_startfile test_winapi test_winconsoleio test_winreg test_wmi

10 tests skipped (resource denied):
    test_curses test_peg_generator test_smtpnet test_socketserver
    test_tkinter test_ttk test_urllib2net test_urllibnet test_winsound
    test_zipfile64

449 tests OK.

Total duration: 30 min 22 sec
Total tests: run=43,108 skipped=1,640
Total test files: run=462/472 skipped=13 resource_denied=10
Result: SUCCESS
ubuntu@ubuntu:~/cpython$ 
```
Full Output: [test-output.txt](https://github.com/python/buildmaster-config/files/14547506/test-output.txt)

> If Python doesn't build or if some tests are failing, are you going to propose fixes?

Yes, I will do my best.

**Comment by furkanonder** [comment]
> @furkanonder: Tell me if you need help to create a PR to add a worker. See @zware's comment.

I created a [PR](https://github.com/python/buildmaster-config/pull/474) to add a worker. Can you review it?
