### ISSUE TITLE
New worker request: arm64-ios-simulator

### ISSUE THREAD

**Issue by freakboy3742** [python/buildmaster-config#475]
### Username

freakboy3742

### GitHub username

@freakboy3742

### Name

Russell Keith-Magee

### Email address

russell@keith-magee.com

### Password status

I need a new owner password

### Processor architecture

ARM64

### Operating System

iOS

### Anything special about the worker?

Required for PEP 730, to test the patches introduced under the meta issue python/cpython#114099.

Builds must be run single process, resulting in an estimated wall-clock duration of ~15m for a single test run.

A specific iOS version hasn't been specified as part of this buildbot definition. The expectation is that the Buildbot will track the current default (i.e., most recent) iOS image shipping with Xcode, and Xcode will be updated regularly as part of regular system maintenance.

**Comment by vstinner** [comment]
@zware @pablogsal: Can you handle this request? I don't manage passwords anymore.

**Comment by vstinner** [comment]
@freakboy3742: Can you prepare a PR to add your worker?

**Comment by freakboy3742** [comment]
@vstinner I'm currently working on setting up the configuration; I submitted this PR because I was following the Buildbot setup guide which advises [posting a PR to discuss setting up the worker and obtain the workername and password](https://devguide.python.org/testing/new-buildbot-worker/#preparing-for-buildbot-worker-setup).

**Comment by vstinner** [comment]
> I need a new owner password

Done.

I leave the issue open until I see the worker running in practice :-)

**Comment by vstinner** [comment]
The worker is running but failing. Failures can addressed in following PRs, I close this issue.

**Comment by freakboy3742** [comment]
[iOS buildbot is now passing](https://buildbot.python.org/all/#/builders/1380/builds/17)
