### ISSUE TITLE
Issues after upgrading to buildbot 4.0

### ISSUE THREAD

**Issue by vstinner** [python/buildmaster-config#498]
Hi,

While trying to update requirements to fix a security issue, I upgrade buildbot from 3.x to 4.0: https://github.com/python/buildmaster-config/pull/497

The `./venv/bin/buildbot upgrade-master /data/buildbot/master` command was run by Salt and the buildbot server is running fine.

... but, the "Release status" page is gone! I think that we have to follow https://docs.buildbot.net/4.0.0/manual/upgrading/4.0-upgrade.html#custom-plugins guide to upgrade our plugins.

**Comment by vstinner** [comment]
I replaced buildbot-wsgi-dashboards dependency with buildbot-react-wsgi-dashboards: it was worse, buildbot failed to even start:

```
    (...)
    File "/srv/buildbot/venv/lib/python3.9/site-packages/buildbot/www/service.py", line 225, in reconfigServiceWithBuildbotConfig
      self.setupSite(new_config)
    File "/srv/buildbot/venv/lib/python3.9/site-packages/buildbot/www/service.py", line 325, in setupSite
      self.configPlugins(root, new_config)
    File "/srv/buildbot/venv/lib/python3.9/site-packages/buildbot/www/service.py", line 302, in configPlugins
      raise RuntimeError(f"could not find plugin {key}; is it installed?")
  builtins.RuntimeError: could not find plugin wsgi_dashboards; is it installed?
```

**Comment by vstinner** [comment]
Currently, the dependencies are:

```
buildbot@buildbot:/srv/buildbot$ venv/bin/python -m pip list|grep buildbot
buildbot                 4.0.0
buildbot-console-view    4.0.0
buildbot-grid-view       4.0.0
buildbot-waterfall-view  4.0.0
buildbot-worker          4.0.0
buildbot-wsgi-dashboards 4.0.0
buildbot-www             4.0.0
```

I also asked for help on #buildbot IRC channel.

**Comment by vstinner** [comment]
@pablogsal @ambv @encukou: Do you have any idea on how to debug such buildbot issue? Sorry for breaking the buildbot "Release Status" page by mistake :-(

**Comment by vstinner** [comment]
`https://buildbot.python.org/all/#/builders` page loads `https://buildbot.python.org/all/api/v2/builders` which fails with HTTP 404 error, whereas it should load `https://buildbot.python.org/all/api/v2/builders` (`all/` is missing in the API URL).

**Comment by vstinner** [comment]
cc @zware

**Comment by zware** [comment]
> `https://buildbot.python.org/all/#/builders` page loads `https://buildbot.python.org/all/api/v2/builders` which fails with HTTP 404 error, whereas it should load `https://buildbot.python.org/all/api/v2/builders` (`all/` is missing in the API URL).

I got this partially working with a hack to the Nginx config; I'll try to get it fully working and submit a PR to the Salt config.

**Comment by vstinner** [comment]
Maybe we should simply drop `all/` from the URL and use a "regular" `https://buildbot.python.org/` home URL?

**Comment by vstinner** [comment]
wsgi_dashboards in https://buildbot.python.org/all/?#/about says:

[{"name":"release_status","caption":"Release Status","app":"'flask.app.Flask' not yet IConfigured","order":2,"icon":"rocket"}]

Oh, there is a Flask error.

**Comment by vstinner** [comment]
> https://buildbot.python.org/all/#/builders page loads https://buildbot.python.org/all/api/v2/builders which fails with HTTP 404 error, whereas it should load https://buildbot.python.org/all/api/v2/builders (all/ is missing in the API URL).

I reported a separated issue: https://github.com/buildbot/buildbot/issues/7776

**Comment by zware** [comment]
With python/psf-salt#372 merged and deployed, the web UI is at least mostly back (without the `/all` prefix).  Release status still needs a fix, but that's beyond me for right now.

**Comment by vstinner** [comment]
It seems like buildbot 4.0 is most fully functional. The Release Status page is available, but it's not fully rendered.

"Releasable" versions only contain the following HTML in their "panel-body":

```
<div style="text-align: center;">
    <i class="fa fa-check" style="font-size:48px;color:green;"></i>
</div>
```

"Not Releaseable" versions only contain the following HTML in their "panel-body":

```
<div> <buildsummary buildid="1539736" condensed="1"> </buildsummary></div>
```

AngularJS is supposed to handle `<buildsummary />`, but I didn't understand if buildbot 4.0 still uses AngularJS or switched to React.

**Comment by encukou** [comment]
I'm back from EuroPython now.

For me it's not only the custom page that's misbehaving:
- Console & Grid views are down as well (stuck on a Loading spinner)
- Waterfall loads, but only shows the header
- In Builds/Builders, cells in the "Builds" column are stuck at "Loading..."

All show 504 (Gateway Timeout) HTTP responses to various API requests. I guess the pages will load if the server was lass busy.

---

According the the 4.0 upgrade instructions, all plugins do need to be rewritten to use React. (They recommend doing it before the big update, but I guess that's not an option any more.)

Does anyone here already know React, or should I learn it?

**Comment by pablogsal** [comment]
All the pages you mention are supposed to be in the included buildbot package so there is nothing we need to rewrite in our side. Can you confirm this with the buildbot team perhaps?

**Comment by vstinner** [comment]
Be careful of old URLs including /all/.

**Comment by encukou** [comment]
Right, the pages I mentioned are part of Buildbot; I opened https://github.com/buildbot/buildbot/issues/7820.

We do need a React rewrite for the release dashboard, which is a custom plugin.
According to [dashboard docs](https://docs.buildbot.net/4.0.0/manual/customization.html#writing-dashboards-with-flask-or-bottle), there still is an AngularJS application, but that's probably stale docs.

**Comment by encukou** [comment]
I also get 404 on JS and CSS files: https://github.com/buildbot/buildbot/issues/7439

**Comment by vstinner** [comment]
I created https://github.com/buildbot/buildbot/issues/7826 "buildbot 4.0: Builders page doesn't limit to 25 builders per page".

**Comment by vstinner** [comment]
> In Builds/Builders, cells in the "Builds" column are stuck at "Loading..."

The problem may be related to https://github.com/buildbot/buildbot/issues/7826 : lack of pagination. Loading all data for 100 or 200 builders take too long, and a timeout somewhere kill the request, so the UI is stuck at "Loading...".

If you limit the Builders view by clicking on a tag, the Builds column can be properly loaded.

**Comment by vstinner** [comment]
The Waterfall View is truncated, the view seems to be limited to like 100 pixels!?

![Screenshot 2024-07-17 at 23-11-05 Buildbot](https://github.com/user-attachments/assets/be9a9754-c33d-4419-8b48-a4e4caf2814b)

**Comment by vstinner** [comment]
I changed the Release Status page to an ugly but working page: https://github.com/python/buildmaster-config/commit/e5d6b0672b9c189a64c2c09eb91d77e20c4c7cdd

**Comment by encukou** [comment]
Thank you!

**Comment by encukou** [comment]
I found another issue: https://github.com/python/buildmaster-config/issues/509

**Comment by pablogsal** [comment]
I think it's time to rollback the upgrade, the buildbot page it's certainly less usable and the release dashboard it's broken and everything feels either slower or slightly broken.

**Comment by edelsohn** [comment]
Each release of Buildbot has been more bloated and slower.  That apparently is progress.  It's more features!  It's not going to get better.  Buildbot developers behave as if they are funded by cpu and memory manufactures to encourage system upgrades.

**Comment by pablogsal** [comment]
@encukou could you please revert https://github.com/python/buildmaster-config/commit/e5d6b0672b9c189a64c2c09eb91d77e20c4c7cdd and the buildbot 4.0 upgrade PRs?

**Comment by pablogsal** [comment]
Also, I think we should bring this up with the buildbot project. We are probably among their heavier users and I am not sure if they are informed of all the problems we are having

**Comment by zware** [comment]
> I think it's time to rollback the upgrade, the buildbot page it's certainly less usable and the release dashboard it's broken and everything feels either slower or slightly broken.

What's broken other than our custom release dashboard?  I'm not seeing the same "everything is slower"; on the contrary, everything actually seems rather snappier since a selective pruning of the database.

We did rush into 4.0, but I'm not convinced that a downgrade is worth the hassle.

**Comment by pablogsal** [comment]
> What's broken other than our custom release dashboard? I'm not seeing the same "everything is slower"; on the contrary, everything actually seems rather snappier since a selective pruning of the database.

For me loading any page requires more than half a minute, including the builder list, the workers and the waterfall view. Specially slower is the page listing the builds for a given builder.

Additionally the web API takes much more to respond.

The only view that remains unaffected is the single build view where the logs can be inspected.

**Comment by vstinner** [comment]
> For me loading any page requires more than half a minute, including the builder list

That's the bug https://github.com/buildbot/buildbot/issues/7826 : if you filter by "3.x" tag, it's quite fast to load the page.

**Comment by encukou** [comment]
> @encukou could you please revert https://github.com/python/buildmaster-config/commit/e5d6b0672b9c189a64c2c09eb91d77e20c4c7cdd and the buildbot 4.0 upgrade PRs?

I can certainly try, if that's the consensus, but I don't think it's a good idea, now that the upgrade is done. While we didn't follow the 3→4 upgrade guide, a 4→3 downgrade doesn't even have a guide AFAIK.

I don't have measurements, but Buildbot felt this slow even before the update.

**Comment by vstinner** [comment]
> Specially slower is the page listing the builds for a given builder.

It seems like listing builds of a builder is also affected by https://github.com/buildbot/buildbot/issues/7826 : there is no pagination, it just loads ALL builds. That's where @zware work to remove old build would be interesting.

**Comment by pablogsal** [comment]
> I don't have measurements, but Buildbot felt this slow even before the update.

I didn't gather times from before the update but I can tell you that at least on my side this is a noticeable regression after the upgrade.

**Comment by vstinner** [comment]
> The problem may be related to https://github.com/buildbot/buildbot/issues/7826 : lack of pagination.

Good news: they reimplemented pagination, released buildbot 4.1 with the change, I deployed the new version, and listing Builders now takes 1 second instead of failing with timeout :-) The page now lists 25 builders (with pagination) instead of 735 builders :-)

**Comment by vstinner** [comment]
@pablogsal:
> For me loading any page requires more than half a minute, including the builder list, the workers and the waterfall view. Specially slower is the page listing the builds for a given builder.

I tested mentioned pages and they now take under 10 seconds to render.

I suggest to close this issue. If you still have issues with buildbot 4.x, I suggest to report the issue upstream. They are reactive, they fixed the pagination issue that I reported.

**Comment by vstinner** [comment]
> On Firefox, the Waterfall View is truncated, the view seems to be limited to like 100 pixels!?

Oh, it's only on Firefox. It works on Chromium. I reported the issue upstream: https://github.com/buildbot/buildbot/issues/8139
