### ISSUE TITLE
Firefox can’t establish a connection to the server at wss://buildbot.python.org/all/ws

### ISSUE THREAD

**Issue by vstinner** [python/buildmaster-config#501]
When trying to load the URL https://buildbot.python.org/all/#/builders?tags=%2B3.x&tags=%2Bstable Firefox logs an error in the Javascript console:

> Firefox can’t establish a connection to the server at wss://buildbot.python.org/all/ws

**Comment by vstinner** [comment]
Maybe something is missing in our nginx proxy configuration? See maybe this doc: https://docs.buildbot.net/latest/manual/configuration/www.html#reverse-proxy-configuration

cc @zware @ambv

**Comment by zware** [comment]
Yes, need to add a rewrite to the `/ws` location as well as `/`.

**Comment by zware** [comment]
Fixed in python/psf-salt#376.
