### ISSUE TITLE
New worker request: mhsmith-android-arm64

### ISSUE THREAD

**Issue by mhsmith** [python/buildmaster-config#511]
### Username

mhsmith

### GitHub username

@mhsmith

### Name

Malcolm Smith

### Email address

smith@chaquo.com

### Password status

I need a new owner password

### Processor architecture

ARM64

### Operating System

macOS hosting an Android emulator

### Anything special about the worker?

Required for Android to reach Tier 3 status (PEP 738). I will create a configuration PR in the next few days.

**Comment by zware** [comment]
I've sent you an email with the password that you can use.  We'll need to have merged the configuration before it's useful to you, though :)

**Comment by itamaro** [comment]
Looks like this is done now
