### ISSUE TITLE
Links from GitHub to buildbot.python.org are broken

### ISSUE THREAD

**Issue by mhsmith** [python/buildmaster-config#512]
For example, https://github.com/python/cpython/pull/121595#issuecomment-2293190400 contains a link to:

https://buildbot.python.org/#builders/1431/builds/376

The correct URL has an extra slash:

https://buildbot.python.org/#/builders/1431/builds/376

**Comment by zware** [comment]
I thought I had fixed that already, but apparently I missed one :(.  Fix incoming.
