### ISSUE TITLE
`edelsohn-fedora-ppc64` worker down

### ISSUE THREAD

**Issue by zware** [python/buildmaster-config#528]
@edelsohn or @stratakis, what is the status of this worker?  Was it meant to be removed with `edelsohn-fedora-ppc64le` in #167?

**Comment by edelsohn** [comment]
Please remove the worker. I believe that it is/was a Big Endian worker.  I have no plans to resurrect it or maintain it.

**Comment by zware** [comment]
Thanks for the confirmation!
