### ISSUE TITLE
Add PGO builds on Windows to buildbots

### ISSUE THREAD

**Issue by mdboom** [python/buildmaster-config#560]
# Feature or enhancement

### Proposal:

We currently don't have any build bot coverage that tests PGO on Windows.  This means we land code that breaks the Windows release build not all that infrequently (examples over the last 12 months: python/cpython#113655, python/cpython#125217, python/cpython#123153, python/cpython#122921).

It would be nice to add this to existing buildbots, but I know our Windows buildbots are few, and PGO builds are time consuming.  Cc'ing the Windows buildbot owners for discussion: @ambv, @itamaro, @db3l.

As an aside, there is plenty of [PGO coverage on the Linux buildbots](https://buildbot.python.org/#/builders?tags=%2Bpgo), but that's largely irrelevant to the problem as it's an entirely different compiler toolchain.  There is no PGO coverage on macOS either, but I have never seen that break -- if we want that for completeness, I suggest we file another issue to track that.

### Has this already been discussed elsewhere?

No response given

**Comment by zware** [comment]
I've opened #561 for this.  I'm trying something new in sharing this builder between both of our workers, @db3l.  It's a hack, but hopefully it works out :)

**Comment by zware** [comment]
Done: https://buildbot.python.org/#/builders/1620

**Comment by mdboom** [comment]
Thanks, all!

**Comment by itamaro** [comment]
opened #565 to add a Windows PGO NoGIL builder
