### ISSUE TITLE
Force scheduler schedules builds for all builders

### ISSUE THREAD

**Issue by zware** [python/buildmaster-config#66]
Rather, it should be possible to select a branch or specific builder(s) to force.

**Comment by pablogsal** [comment]
@zware  Hummm....Unless I am missing something, if you go to a particular builder page and click "force", only that builder is scheduled:

1
![test](https://user-images.githubusercontent.com/11718525/48460949-33e6b300-e7c9-11e8-98be-94acdfbf6747.png)
2
![test2](https://user-images.githubusercontent.com/11718525/48460954-36490d00-e7c9-11e8-9b18-dc5c98e8f08d.png)
3
![test3](https://user-images.githubusercontent.com/11718525/48460955-3812d080-e7c9-11e8-9fca-cd6c9a0ca339.png)

meanwhile, in other builder:

![test4](https://user-images.githubusercontent.com/11718525/48460970-4c56cd80-e7c9-11e8-823f-587924f38186.png)

**Comment by pablogsal** [comment]
Relevant: Recently, I was testing the REST API for the Force Scheduler and I schedule a build in every builder at the same time (maybe that is the origin of this issue).

**Comment by vstinner** [comment]
This issue was created 3 years ago. I didn't face this issue. Do we really have to do anything?

**Comment by zware** [comment]
Probably not :)
