### ISSUE TITLE
synchronization of class names for AIX systems compared to other platforms

### ISSUE THREAD

**Issue by aixtools** [python/buildmaster-config#80]
While synchronization may not be hot - I do notice what feel like incorrect names.

I would expect the basename, e.g. "AIXBuild" to be the generic aka starting point and then other names for when arguments are added. This was done - there is a classname AIXBuildWithGcc - except there is no configure argument "--with-gcc". Further, it magically deletes the argument "--without-computed-gotos" that the class AIXBuild has.

So, the coming PR will contain my suggestion:

classnames "AIXBuild", and "AIXBuildWithoutComputedGotos"

**Comment by zware** [comment]
This was done by #81.
