### ISSUE TITLE
Windows ARM32 worker on too many branches

### ISSUE THREAD

**Issue by zooba** [python/buildmaster-config#90]
Thanks to #89 we now have a Windows ARM32 buildbot.

Looking at https://buildbot.python.org/all/#/builders though, I see it's attached to 2.7, 3.6 and 3.7 branches, while the support is only coming in for 3.x:
![image](https://user-images.githubusercontent.com/1693688/57808518-63df2680-7718-11e9-819e-6193fc682977.png)

Can/should we restrict the buildbot to only the 3.x branch? I assume it's just going to fail to build against the other branches.

**Comment by zooba** [comment]
Ping @zware @paulmon

**Comment by zware** [comment]
Fixed in ca0ef08.
